### ISSUE TITLE
Problems with PhenoGraph using Scaffold data

### ISSUE THREAD

**Issue by CNicholasMDA** [dpeerlab/cyt3#1]
Hello,
My team is having difficulty performing analysis of mass cytometry data using cyt3. Specifically we are performing Scaffold analysis, transforming the .RData file to .FCS and then running PhenoGraph in cyt.  We are getting the following error and are not certain why. Can anyone offer insight? Thank you!

<cmd-i>_Files loaded: 0.865882s
Allocated space for data: 0.747466s
Read data into session: 0.25032s
Finding 30 nearest neighbors...
Index of element to remove exceeds matrix dimensions.
 
Error in phenograph (line 42)
    IDX(:,1) = []; D(:,1) = [];
 
Error in cyt>phenoEach (line 5721)
        [clusterLable,~,~,ID] = phenograph(data, k_neigh,'distance',distance);
 
Error in gui_mainfcn (line 95)
        feval(varargin{:});
 
Error in cyt (line 85)
    gui_mainfcn(gui_State, varargin{:});
Error while evaluating Menu Callback_ <cmd-i>

**Comment by ManuSetty** [comment]
Hello

Thank you for your interest in cyt3. Unfortunately we are not actively maintaining the GUI at this point. If you are interested specifically in running Phenograph, we recommend using our Python module for Phenograph: https://github.com/dpeerlab/PhenoGraph. 

The package above does not have a GUI, but Wishbone, another tool from the lab (https://github.com/dpeerlab/wishbone) contains a Jupyter notebook that allows us to run Phenograph and cluster cytof data: http://nbviewer.jupyter.org/github/ManuSetty/wishbone/blob/master/notebooks/Wishbone_for_mass_cytometry.ipynb

Let us know if this helps with the issue.

**Comment by CNicholasMDA** [comment]
Thanks Manu - I will check it out.  I'll also wait to see if any of the community members have an insight.  Thanks again for your time!
